# Exported from Render on 2024-04-26T20:52:37Z
services:
- type: web
  name: Extract_CV_info-1
  runtime: python
  repo: https://github.com/ajaykumar81536/Extract_CV_info
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn -w 4 -b 0.0.0.0:8080 app:app
- type: web
  name: Extract_CV_info
  runtime: python
  repo: https://github.com/ajaykumar81536/Extract_CV_info
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
version: "1"
